### ISSUE TITLE
Mocking SMS/SQS 

### ISSUE THREAD

**Issue by OAGr** [iHiD/propono#63]
I was curious if you had any strategies for using applications without AWS access.  Perhaps we could mock sms/sqs with a simple but functional esb in the backend.  I realized there exists issue  https://github.com/meducation/propono/issues/45 which discusses simple mocking of propono methods for testing, but I am more curious about setting up application environments for user and development testing.

Has anyone ended up trying out ActiveJob or similar for the purpose?

**Comment by OAGr** [comment]
Found this issue which discusses, closing.
https://github.com/meducation/propono/issues/45

**Comment by iHiD** [comment]
There's a package somewhere that mocks AWS. Can't remember what it's called but maybe @ccare, @mmmmmrob or @malcyL can?

Personally, I tend to have two test sets. One fully stubbed for unit testing and then one that does integration testing against a development AWS account.

Give me a little more info about your usecase and we can brainstorm.

**Comment by dougal** [comment]
#102 allows passing of alternative endpoints to the SNS and SQS clients. This could be used to use a local AWS alternative such as [GoAWS](https://github.com/p4tin/goaws) to mock out AWS for testing.

Example config for Propono to use GoAWS:

```ruby
client = Propono::Client.new do |config|
  config.aws_options = {
    endpoint:            'http://localhost:4100'  
  }
end
```
