### ISSUE TITLE
Use IAM role instead of access & secret keys

### ISSUE THREAD

**Issue by michaelfich** [iHiD/propono#70]
I am attempting to refactor an application which has been successfully using this gem.  Currently it uses AWS access & secret keys in the propono config, however when refactoring it to use an IAM role, it currently throws an error at the following line:

https://github.com/iHiD/propono/blob/master/lib/propono/configuration.rb#L38

I believe this is just because `access_key` and `secret_key` are not being initialized, so unless you specifically set those values, an error will be thrown.

**Comment by michaelfich** [comment]
I've added a PR which I think should resolve this issue: https://github.com/iHiD/propono/pull/71

**Comment by iHiD** [comment]
Hi @michaelfich.

Thanks for opening the issue and being proactive with the PR. That said, we use iam roles with this gem and haven't had issues so I'm a bit confused :)

The `nil?` guard in the code your PR edits is deliberate to stop people forgetting to set keys and to provide a helpful error, so I'm reluctant to change that. In my head, it feels like fixing the symptom not the cause. 

[This line](https://github.com/iHiD/propono/blob/a092078a7abd85fe501d3488a835cd5ee371be28/lib/propono/components/aws_config.rb#L14) should guard against what you're seeing:  Do you have a fuller stack trace so I can see what's causing the line to reference to be hit please?

Thanks!

**Comment by michaelfich** [comment]
Hey @iHiD,

Yeah totally, I thought that setting (`use_iam_profile`) would do it as well.  I'll take another look tomorrow.

Thanks for taking a look!
