### ISSUE TITLE
Message Visibility Timeout is too short for some classes of tasks

### ISSUE THREAD

**Issue by dougal** [iHiD/propono#80]
# Failure case

By default the timeout visibility of a message in an SQS queue is 30 seconds. If processing a video, say, which takes an hour to process, the worker only has exclusivity on the message for the first 30s of the processing time. After that (depending on the queue setup, I haven't looked closely at it), the message is either dequeued for other workers to pick up, or put in a dead letter queue.

This can result in multiple workers processing the same message, or a single worker processing the same message repeatedly.

# Suggested Solution

`Aws::SDK::SQS#receive_message` allows setting of a `visibility_timeout` attribute (0s to 12h, defined in seconds). Thus it would seem that setting visibility_seconds on the `listen` method would prevent this issue.

    Propono::Client.new.listen('long-running-tasks', visibility_timeout: 3600) do |message|
      puts "I just received: #{message}"
    end

Perhaps a better, and less AWS specific, key might be something like `exclusivity_timeout_seconds`.

**Comment by iHiD** [comment]
@dougal Thanks.

You think the right place for this is on `listen`, as opposed to in the config? I think I do.

**Comment by dougal** [comment]
It could be a config item, but then it applies globally. There are some tasks for which a long visibility could be a disadvantage. I prefer placing the config on `listen`.

**Comment by iHiD** [comment]
Implemented on `2.1.0`
