### ISSUE TITLE
How do I use GoAWS?

### ISSUE THREAD

**Issue by spkprav** [iHiD/propono#84]
https://github.com/p4tin/goaws

I am trying to change the endpoint for AWS to use local environment for SQS and SNS, but I couldn't find the right place to customize it. Any idea where I can use the local URL?

Thanks,
Praveen

**Comment by iHiD** [comment]
Hi @spkprav - Nice idea.

@dougal is working on this and hopefully we'll release a version including it some time soon :)

**Comment by A-Scott-Rowe** [comment]
@spkprav 
We have solved this problem (Hackily) by monkey patching and overriding the Propono::AwsConfig class 

```
module Propono
  class AwsConfig
    def aws_options
      {
        aws_access_key_id: 'x',
        aws_secret_access_key: 'x',
        region: '',
        host: <goAWS host>,
        port: 4100,
        scheme: 'http'
      }
    end
  end
end
```

This same override can be done on both publisher and  consumer, although we needed to make other patches on the consumer machine.

**Comment by dougal** [comment]
@spkprav Version 3.0 allows [passing a config hash to the AWS clients](https://github.com/iHiD/propono/blob/main/README.md#aws-configuration), thus making using GoAWS trivial.

```ruby
client = Propono::Client.new do |config|
  config.aws_options = {
    endpoint:            'http://localhost:4100'  
  }
end
```

This was added in #102.
