### ISSUE TITLE
Update repository

### ISSUE THREAD

**Issue by gssbzn** [iHiD/propono#86]
Hi, I'm seeing that a new version of the gem has been released (https://rubygems.org/gems/propono/versions/2.1.0) but I can't see any changes published to this repo.
Is this still the main page for the project or has it been changed?
Probably update https://github.com/iHiD/propono/blob/d0c36850fa6a2409f5e2919fa91a87133a2549af/propono.gemspec#L13 to reflect this changes
or update the repository with the latest revision and tags

**Comment by iHiD** [comment]
Thanks. [Pushed](https://github.com/iHiD/propono/blob/master/CHANGELOG.md#210--2017-03-14).
