### ISSUE TITLE
Multiple listen blocks on the same file

### ISSUE THREAD

**Issue by arieliten** [iHiD/propono#92]
Hi, what's the right approach to follow if I want to listen to many different topics on the same script?
For the subscriber part of my pub/sub architecture I want to have one script running (as a daemon on the background) that can listens to multiple topics and do something depending on the topic.
I have the following script (inside a Rails app):
```ruby
#!/usr/bin/env ruby
require File.expand_path('../config/environment.rb',  __FILE__)

# setting up the client
client = Propono::Client.new
client.config.access_key = my_access_key
client.config.secret_key = my_secret_key
client.config.queue_region = region
client.config.application_name = "my-unique-app-name"

# listening to different kind of events so we can respond according
client.listen("topic-1") do |message|
  puts "Topic 1: #{message}"
  # do something related to topic-1
end

client.listen("topic-2") do |message|
  puts "Topic 2: #{message}"
  # do something related to topic-2
end

client.listen("topic-3") do |message|
  puts "Topic 3: #{message}"
  # do something related to topic-3
end
```
However this is not working and if I run the above ☝️script, it'll only respond to messages/topics happened on `topic-1`, and I found it's because the `listen` method is implemented as an endless `loop do` block, so it never returns.

Is there a way to accomplish the above without having to separate each `listen do` block into its own script? I don't want to have multiple scripts (one per topic) running on the background individually.

Thanks

**Comment by iHiD** [comment]
I'd use threads. From memory something like this?

```ruby

threads = []
threads << Thread.new do 
  client.listen("topic-1") do |message|
  end
end

threads << Thread.new do 
  client.listen("topic-2") do |message|
  end
end

threads.join
```

**Comment by iHiD** [comment]
You could also probably just do `ThreadGroup::Default.list.each(&:join)` and avoid the `threads` array altogether.

**Comment by arieliten** [comment]
Ok @iHiD , I'll try that and will let you know. Thanks for your response

**Comment by arieliten** [comment]
Hey @iHiD, it worked! I'm closing this. Thanks

**Comment by iHiD** [comment]
Great :) Thanks for letting me know :)

**Comment by arieliten** [comment]
Hey @iHiD , another quick question: what would you use if you want to have a script running in the background (daemon(?)) in the context of a Rails app? I was trying [this approach](http://michalorman.com/2015/03/daemons-in-rails-environment/) as a rake task but not sure if it's the right approach and also how to integrate with tools like [foreman](https://github.com/ddollar/foreman). Any suggestion?

**Comment by dougal** [comment]
Hi Ariel.

We implement listeners inside service classes, then call them from whatever daemon/script runner is on the system using a Rails runner:

```
bundle exec rails runner "ListenerName.listener!"
```

This could be used with Foreman, SystemD, etc.
